### ISSUE TITLE
JSON endpoint

### ISSUE THREAD

**Issue by theS1LV3R** [httpstatuses/httpstatuses#12]
A JSON endpoint could be pretty useful, perhaps something like `{code}.json`?

**Comment by mgernand** [comment]
For now you can use the JSON endpoint on my own version of the site: [https://httpstatuscodes.io](https://httpstatuscodes.io)

You can access the JSON endpoint like you mentioned: [https://httpstatuscodes.io/201.json](https://httpstatuscodes.io/201.json)

You get a response like this:

```js
{
  location: "https://httpstatuscodes.io/201",
  statusCode: 201,
  title: "Created",
  category: "Success",
  description: "The request has been fulfilled and has resulted in one or more new resources being created."
}
```

**Comment by jkulton** [comment]
Added in https://github.com/httpstatuses/httpstatuses/pull/21. Thanks!
