### ISSUE TITLE
Severely outdated metalsmith build

### ISSUE THREAD

**Issue by webketje** [httpstatuses/httpstatuses#14]
Hi there,

I'm the maintainer of metalsmith and caught wind of this project due to the spike in traffic to the metalsmith.io website your recent blog post created (thx, and I was also fond of the original httpstatuscodes.com) 🙂

Should you be interested, Metalsmith is now at v2.4.3 and a lot of "core" plugins have been moved/ added/ renamed/ adopted under the `@metalsmith` org. A little overview to help you upgrade:

- metalsmith-ignore => @metalsmith/remove
- collections, layouts and markdown have all moved to @metalsmith/<plugin>
- there is a news @metalsmith/sass which uses dart-sass instead of the deprecated libsass

A lot of these updates contain dependency vulnerability fixes as well as new features, but it should take little time as most updates are fully backwards-compatible.
Cheers!

**Comment by jkulton** [comment]
Thanks for this info @webketje, it's very helpful!

I will explore getting us onto something more recent.
