### ISSUE TITLE
JSON endpoints?

### ISSUE THREAD

**Issue by luizen** [httpstatuses/httpstatuses#23]
I saw today this announcement on the page:

_`✨ New: JSON endpoints! Just append .json to any code's path. See [200.json](https://httpstatuses.io/200.json).`_

And when opened, this is the result:
```
{
  "status_code": 200,
  "title": "OK",
  "description": "The request has succeeded.",
  "category": "Success",
  "html_url": "https://httpstatuses.io/200"
}
```

Is this returned object based on any standards? I was wondering whether the return should be based on ProblemDetails instead [(rfc7807)](https://datatracker.ietf.org/doc/html/rfc7807), which is a more known standard :)

**Comment by jkulton** [comment]
👋 Hey there!

Do you have any fields in particular you think would be best renamed? (or added/removed?) I'm certainly open to rethinking the naming of the fields we return, though in general I'd like to avoid removing any fields outright.

I need to think a bit more on whether adopting the linked standard outright makes sense. From my reading, RFC7807 outlines a spec for **non-success** HTTP responses to return additional details on the problem the actual HTTP request encountered, in the form of a standardized JSON body.

**Comment by luizen** [comment]
Hi! :)

> From my reading, RFC7807 outlines a spec for **non-success** HTTP responses to return additional details on the problem the actual HTTP request encountered, in the form of a standardized JSON body.

Yes, that's right.

Not that I wish any renaming/additions :) I was just wondering whether you based that idea on any known standards. But I guess not, right?

One last question: is the idea of having the JSON endpoints so that one could fetch specific HTTP status code details in a SPA scenario, for instance?

Thanks!

**Comment by jkulton** [comment]
> Not that I wish any renaming/additions :) I was just wondering whether you based that idea on any known standards. But I guess not, right?

Oh, gotcha! Yes that's correct. The original idea came from https://github.com/httpstatuses/httpstatuses/issues/12!

> One last question: is the idea of having the JSON endpoints so that one could fetch specific HTTP status code details in a SPA scenario, for instance?

Although I didn't have that in mind, it's certainly an idea you could try out! You'd still need to fetch the endpoint from your backend before sending it to the SPA for CORS reasons.

I would also ensure the error can render even without the details, otherwise if you _need_ a response from httpstatuses in order to render an error to the user your app's availability immediately becomes tethered to an external service.

**Comment by luizen** [comment]
> Although I didn't have that in mind, it's certainly an idea you could try out! You'd still need to fetch the endpoint from your backend before sending it to the SPA for CORS reasons.
> 
> I would also ensure the error can render even without the details, otherwise if you _need_ a response from httpstatuses in order to render an error to the user your app's availability immediately becomes tethered to an external service.

Good points ;) Thanks!
